# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’
pod "PinterestSDK", :git => "git@github.com:pinterest/ios-pdk.git"

target 'What\'s For Dinner?' do

end

target 'What\'s For Dinner?Tests' do

end

